name: "04_App_Acr"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
##### PLAN A DEPLOYMENT #####
  Plan_Dev_Deploy:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    environment: null        
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dev TF Plan Deploy
        uses: 9718448/securehubv2-plan@v1.2.0
        with:
          path: app
          plan_mode: deploy
          tf_version: latest
          tf_vars_file: config-dev.tfvars
          tf_key: acr-appdev000
          enable_TFSEC: true
          az_resource_group: rg-tfcore
          az_storage_acc: sa-tfcorebackend
          az_container_name: ghdeploytfstate
          arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
          arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
          arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

##### APPLY DEPLOY #####
  Apply_Dev_Deploy:
    needs: Plan_Dev_Deploy
    runs-on: ubuntu-latest
    environment: Development    
    steps:
      - name: Dev TF Deploy
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: 9718448/securehubv2-apply@v1.2.0
        with:
          plan_mode: deploy
          tf_version: latest
          tf_key: acr-appdev000
          az_resource_group: rg-tfcore
          az_storage_acc: sa-tfcorebackend
          az_container_name: ghdeploytfstate
          arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
          arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
          arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}

##### PLAN A DESTROY #####
#  Plan_Dev_Destroy:
#    needs: Apply_Dev_Deploy
#    runs-on: ubuntu-latest
#    if: ${{ github.actor != 'dependabot[bot]' }}
#    environment: null        
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3

#      - name: Dev TF Plan Destroy
#        uses: 9718448/securehubv2-plan@v1.2.0
#        with:
#          path: 04_App_Acr
#          plan_mode: destroy
#          tf_version: latest
#          tf_vars_file: config-dev.tfvars
#          tf_key: acr-appdev000
#          enable_TFSEC: false
#          az_resource_group: rg-tfcore
#          az_storage_acc: sa-tfcorebackend
#          az_container_name: ghdeploytfstate
#          arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
#          arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
#          arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
#          arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
#          github_token: ${{ secrets.GITHUB_TOKEN }}

##### APPLY DESTROY #####
#  Apply_Dev_Destroy:
#    needs: Plan_Dev_Destroy
#    runs-on: ubuntu-latest
#    environment: Development 
#    steps:
#      - name: Dev TF Destroy
#        if: ${{ github.actor != 'dependabot[bot]' }}
#        uses: 9718448/securehubv2-apply@v1.2.0
#        with:
#          plan_mode: destroy
#          tf_version: latest
#          tf_key: acr-appdev000
#          az_resource_group: rg-tfcore
#          az_storage_acc: sa-tfcorebackend
#          az_container_name: ghdeploytfstate
#          arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
#          arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
#          arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
#          arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}